[build]
  command = "npm run build:production"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  # Extend function timeout to 30 seconds for database connections
  timeout = 30
  
# Environment settings for functions
[build.environment]
  # Ensure Prisma uses the correct engines
  PRISMA_ENGINES_MIRROR = "https://binaries.prisma.sh"
  # Force function rebuild
  NETLIFY_FUNCTIONS_CACHE_BUST = "1738330641"

# Static assets must be served first (before API redirects)
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200
  force = false

# API routes redirect to serverless functions
[[redirects]]
  from = "/api/auth/*"
  to = "/.netlify/functions/auth"
  status = 200

[[redirects]]
  from = "/api/admin/*"
  to = "/.netlify/functions/admin"
  status = 200

[[redirects]]
  from = "/api/user/*"
  to = "/.netlify/functions/user"
  status = 200

[[redirects]]
  from = "/api/workspaces/*"
  to = "/.netlify/functions/workspaces"
  status = 200

[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/health"
  status = 200

# All other API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200

# SPA fallback for frontend routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200